// These files are all generated by the scanner from the src/foo_core.zig
// files and protocol xml
pub const client = @import("client.zig");
pub const server = @import("server.zig");
pub const common = @import("common.zig");
